version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.50.23
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  kafka-manager:
    image: sheepkiller/kafka-manager:alpine
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: "192.168.50.23:2181"
      # APPLICATION_SECRET: "letmein" 
    depends_on:
      - kafka
